# Generated by Django 4.0 on 2021-12-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='auth',
            new_name='author',
        ),
    ]
