# Generated by Django 4.0 on 2021-12-19 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_rename_auth_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
